name: yes_ads_solution
description: yes ads solution.

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  another_flushbar: ^1.10.29
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
